version: '3.7'

services:
  mongodb:
    container_name: CC-mongodb
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - kk-data:/data/db
      - kk-log:/var/log/mongodb


volumes:
  kk-data:
    driver: local
  kk-log:
    driver: local

